<a href="https://colab.research.google.com/github/katkaramruta64/AI-ML/blob/main/DecisionTreeRegressor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import required libraries for data analysis and visualization
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('USA_Housing.csv')

In [3]:
df.head()

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price,Address
0,79545.458574,5.682861,7.009188,4.09,23086.800503,1.059034e+06,"208 Michael Ferry Apt. 674\nLaurabury, NE 3701..."
1,79248.642455,6.002900,6.730821,3.09,40173.072174,1.505891e+06,"188 Johnson Views Suite 079\nLake Kathleen, CA..."
2,61287.067179,5.865890,8.512727,5.13,36882.159400,1.058988e+06,"9127 Elizabeth Stravenue\nDanieltown, WI 06482..."
3,63345.240046,7.188236,5.586729,3.26,34310.242831,1.260617e+06,USS Barnett\nFPO AP 44820
4,59982.197226,5.040555,7.839388,4.23,26354.109472,6.309435e+05,USNS Raymond\nFPO AE 09386

In [4]:
x=df[['Avg. Area Income','Avg. Area House Age','Avg. Area Number of Rooms','Avg. Area Number of Bedrooms','Area Population']]
y=df[['Price']]

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [6]:
from sklearn.tree import DecisionTreeRegressor
model=DecisionTreeRegressor()
model.fit(x_train,y_train)

DecisionTreeRegressor()

In [7]:
pre= model.predict(x_test)

In [8]:
print(pre)

[1252723.42964037 1140126.18694318 1525601.79137374 1174747.55058413
 1329521.13898328 1664147.63907044 1092130.98139801  874497.26548031
  978766.9138661  1495672.59380075  697212.3669253  1302029.01264354
  945981.52963228 2050594.04550631 1296134.39455469 1144937.61380496
  992773.79157031 1126137.68140858  803919.80647176  814879.20628909
  921396.97525415 1067191.97994647 1522083.94415309 1226180.76798918
 1582605.53510266 1019425.93675783 1012269.46867818 1145804.26928656
  959243.60844873 1673294.24619638 1307506.56506919 1598615.97448642
 1382810.7056157  1251757.19301298 1506656.82602291 1856211.3503596
 1405399.85509825  882057.17059284 1637831.32783463 1411054.31694068
 1369970.61328254 1019880.65305419 1405495.70997487  971099.47539869
 1244789.02200199 1064939.52251981 1159526.15420616 1353488.41646297
 1475700.70966093 1347210.09225497 1739761.3726114  1223100.54249556
  975913.10514971  539483.39661118 1838984.43978839 1899136.5354006
 1131887.76178601 1074263.31723636 1277172.47577458 1468459.95474691
  779207.55461309  539483.39661118 1349743.14639109  943575.13069558
 1181630.62516964 1712282.25936342 1509422.57994316 1005431.45123382
 1851065.49687777 1347904.39530069  927181.06639268 1682708.61686642
 1185160.86107858  881446.11554461  923508.12565049 1409439.06376517
 1010813.70905556  900851.16310952 1771036.92451985  151527.08262656
 1591383.73522    1314770.46994938  404643.60224269  377618.96990142
 1357575.85161511  615506.80108119  762130.46225016  907462.45120202
 1537475.78982883 1401767.90425176 1383508.06161512 1400609.03407812
  768751.9005441  1410362.61309221 1318681.04018215  702321.75232142
 1119992.61883545  845890.24051291 1491838.49444347 1494241.22619044
  426906.18286889 1642164.21611555 1411054.31694068 1961715.86669203
 1921028.56988553 1069851.16160234 1487855.53796449 1222344.20849926
 1714055.83680012 1768705.12527915 1340909.79865687 1374117.06727519
 1703880.21991408 1534479.90656442 1025908.91405283 1646662.91068116
  839194.0689419  1235750.60171707 1054856.032667   1409684.48511891
 1796531.90326573 1594089.24144713 1524845.42190295 1483041.33501214
 1463130.27297894 1271396.51800598  636506.00059899 1105737.46154385
 1247645.40971081 1626592.99106101 1233126.83565239 1027311.5076734
 1588196.23290249 1483848.16937598 1405933.01869925 1233965.83737812
 1649947.15975202 1198725.4871449   589352.39540682 1491290.04865606
 1638632.15072055 1183343.56649345 1537765.66056849 1072914.9964424
 1930802.91896111 1152269.43076739 1233484.4765781  1122320.93263019
 1259357.02326835 1526915.34901312  987434.74983935  974805.99371288
 1291331.51848582 1265927.3597382  1379456.03071087  607873.77275599
 1593331.70871016 1302748.85759648 2033546.78457399 1266747.82953743
 1416648.29730638 1442079.05731339 1208843.27673078 1866035.41497571
 1288426.69390285  576356.03188201  943485.04726778 1752112.60416309
 1051230.0005784  1705546.4122133  1708631.36537014 1063182.69618235
 1928301.78160879  627733.74338638 1590336.41704411 1740404.96743497
 1476989.18350395  724993.88924166  856022.86246386  886536.42837472
  729688.59263174 1105737.46154385  790802.80103481 1107159.78060591
  912422.14642095  491085.82599629 1308465.24004301 1211110.08408249
 1442372.04360411 1271752.43195011 1626893.54722418 1050541.31394844
 1256086.50705911 1228323.22490594 1268134.92922798 1644923.07826232
 1381442.75845971 1518387.14164684 1273067.03602756  629657.61325441
 1187090.94809357 1427551.14496685 1305219.5213491   739870.79364027
  947355.97008645 1306349.9922859  1473540.75993854  994654.40942479
 1094879.77349138 1676770.33057392 1172514.72247399 1289082.363025
 1318681.04018215  951243.85407658  626085.93300465 2056692.76825087
 1144937.61380496  747396.2531268  1510996.43526689 1307506.56506919
 1324022.02462432 1161457.8482887   407718.93821549 1125880.48737074
 1850525.57299623  624482.76358665 1474296.41581626 1283401.78925187
 1415647.55343724 1640990.37846293 1270543.46419449 1222344.20849926
  936864.68783437 1317040.737321   1535152.07371691 1663509.39262403
 1765281.09322946 1173413.5499918   575694.17321584 1663509.39262403
 1644923.07826232 1409318.57746743 1336172.19406627 1457672.90568856
 1774715.48357601  552279.21404665 1159699.96572003 1371311.61628979
 1113373.52000173  624482.76358665 1412449.47858682 1532845.72311946
 1596439.71573262 1381430.63018879 1942640.26532281  774674.05665972
 1789334.85148127 1111085.01689106 1575100.91278732 1675702.22325349
 1219637.36651886  615506.80108119 1814462.35050116  634218.44082844
 2173808.62771574  469262.81557521 1578146.33993396 1356384.6675167
 1221823.70446983 1043548.60910841 1713351.3941515  1039794.76744782
 1047689.26574636  896944.24427117 1102943.35144492 1114901.97262301
 1662494.73554439 1221823.70446983  578309.08618667 1574582.09092591
 1079745.11850214 1236258.07968267 1131887.76178601 1226180.76798918
 1365036.08375725 1537329.56953615 1056225.68560119  836339.81694587
  607873.77275599 1432252.08107398 1546957.22646191 1467910.56944261
 1535262.44079042 1037147.46740242 2318285.70333662 1381117.70135143
 1302664.41725796 1035976.95286971  404976.36589623 2017174.98942263
  992773.79157031 1669127.07812649 1099788.69803186 1058269.01857032
 1522083.94415309 1596439.71573262 1345296.55443818 1033881.13480054
 1535262.44079042  852703.26367575  958909.19346485 1357575.85161511
 1698198.75137    1306288.2274582  1115013.14745176 1401613.91976932
 1360623.69445693 1568181.61446469 1529452.06177674  780934.03796334
 1591934.19032791 1203623.84084199 1197740.9167664  1062095.46762675
 1268703.8107934   696139.26136292  790802.80103481 1420469.72651892
 1394970.59858557  725040.89595474 1015546.30860722 1084556.02918041
  739027.67583693  517937.58954093  975384.18142202  885920.55324936
 1433006.64542144 1525601.79137374 1044999.34285282 1453381.62430311
 1450619.45728302 1661592.7891103  1463003.05588126 1450619.45728302
 1473680.6037392  1218200.81150872 1291331.51848582 1891949.34783336
 1669127.07812649 1525601.79137374 1037382.57710349 1449033.43225425
 1460450.98147615 1765281.09322946 1145804.26928656 1314245.81999732
 1502451.11371471 1459525.37584855 1109639.99566839 1415073.61418119
 1442079.05731339  524712.76606745 1409439.07587247 1641055.93904464
 1245785.05095909  773360.69798721 1153233.24064009 1412274.48600768
 1491538.49925012  679627.59557721 1325354.50823022 1961715.86669203
  887739.43210392 1457755.97931771 1439506.10155701 1398760.04650839
  923246.86207402  930011.5708874  1367619.92344288 1102821.43818081
 1128895.12495077  385678.16667312 1311379.59631198 1429951.80389933
 1059033.55787012 1345296.55443818 1151006.07752777  859078.64771756
  849153.12252829 1355022.28256669  663732.39689633 1706689.93975441
 1305127.33600235 1463383.48668297 1034218.40185903 1005431.45123382
  744132.70416552 1017374.02335737  818289.76420874 1621982.4180537
  923508.12565049 1378863.68837721 1059113.72127547  729678.62621031
 1598736.40016478 1206250.64775039  880682.30199101  999369.79836461
 1462989.49082137 1633138.09793998 1235750.60171707  606191.86692281
 1479295.57093729 1324022.02462432 1246595.16028817 1049672.24860723
 1403296.25760751 1314635.68969845 1014513.20953143  566896.21232714
 1198313.59809977 1479295.57093729 1104701.23442073 1291759.39266068
 1543357.45351051 1278618.62031414 1649947.15975202  964596.74983993
 1340769.76782914 1222020.82133591 1023943.77512424 1126042.40497141
 1075550.21547577  928950.00324854 1406435.80621744  895737.13338351
 1124424.92666298 1425366.41343315  615506.80108119 1117011.10618471
  980161.6274097  1403176.42908767 1528987.32488161 1174481.06641427
 1357710.96492256 1670950.31275687 1789973.20520199 1049672.24860723
 1069851.16160234 1277780.51220943 1389223.60712147 1156786.0838811
 1795222.73568574  845553.3695012  1713351.3941515   867311.06374705
  635429.23051901 1591383.73522    1179992.28867516 1246830.18842863
 1822987.81972458 1285098.69079136 1304511.89906857 1906024.63648502
  940138.96139873 1234629.59549004 1463442.90828703 1095879.44339972
 1239940.04216681  867311.06374705 1574582.09092591 1007856.26624004
 1396241.19810412 2082236.24379718 1417691.11279291 1757395.78723971
 1191564.19993432  889113.23886125  699787.31904227  841236.16763426
  824540.89636747 1277297.48311534 1251430.92031862 1474379.44008215
 1053484.8692002   629657.61325441 1625166.64848953 1428212.03436286
 1328701.19413566 1251663.85126218 1189069.10469094 1189466.71433408
 1500821.46909593 1389763.82152622 1210573.85526575 1209445.22037353
 1061552.02189048  508951.5668799  1165990.60369677 1517152.58462546
 1376898.05838952 1014513.20953143 1312063.75611738 1391303.78687125
 1257217.28971051  908616.48262409 1296146.93885966  679228.99274684
  950121.56210652 1085943.0760246   624244.94438764  693681.00440279
 1172385.89770456 1094321.88275509  961539.05992365 1577462.03395039
  914231.29230679 1449829.49375026 1025705.13431974 1070240.01962079
 1308231.76941177 1587622.64123856  718869.40064733  803259.61255941
 1060897.6894524  1556786.60019477 1340909.79865687 1127260.12575137
 1182980.60427171 1367142.71669501 1742350.96216896 1838503.99427185
 1792254.81800471 1128895.12495077 1124125.92064897 1317234.04287959
 1373048.09902299 1555497.54638866  608794.2466922  1400104.87076026
 1410362.61309221 1601152.93224701 1575100.91278732 1086181.75307895
 1257101.59289231 1538401.81729363 1471784.00517606 1523801.748313
  845553.3695012  1335883.83118445 1037147.46740242  885709.76428441
 1451930.63128603 2115010.70359761  903301.99333671 1421135.8149541
  601973.00173971  940138.96139873 1206986.88523428 1433614.96674589
 1139072.7722894  1450393.53041457 1184614.08702401 1698198.75137
 1074263.31723636 1616382.93211806 1177744.97309264 1147685.30055025
 1222344.20849926 1555510.3797599  1462422.25607806 1887529.37663517
 1287030.93169089 1232974.142083   1032346.8698248   912422.14642095
 1578766.04995913 1297619.34829872  895845.56548697 1374117.06727519
 1114901.97262301 1249461.56160075  667428.25371631 1381417.24950466
 1399906.4496456  1394132.24138655 1882978.90043677 1795093.03400894
  780934.03796334 1409439.06376517 1175289.16051141  625880.73205376
  893541.45694964 1434240.3558561   635429.23051901  840272.86489232
 1152269.43076739  997448.72807699 1591793.72329709 1152269.43076739
 1049632.18068352 1106261.2737053  1081150.12548381  862376.75334144
 1473680.6037392  1731437.41599478 1115323.01484241 1376898.05838952
 1419345.60730258 1174481.06641427  991892.31748425  143027.36445248
 1315666.87392322 1306288.2274582  1693591.83537762 1267986.687524
 1037147.46740242  813807.6997245   461912.24428417 1455107.45111253
 1027311.5076734  1693591.83537762 1063630.92750045 1851065.49687777
 1706689.93975441 1143203.06786569 1598159.2269511  1557914.88977842
 1836978.48306049  975913.10514971 1470476.98710327 1025908.91405283
 1223261.46230481 1043628.37035454 1380602.55558134 1615346.75000537
 1154126.21568857  635530.84488606 1331897.45684096 1084945.39966764
 1376714.67419885  714148.4147529  1175504.48633204  720059.834808
  982790.87100364 1294647.58916718  994517.04533513 1887529.37663517
 1276448.79204297  820611.47085954 1270390.24846834 1698198.75137
  906419.31790213 1156979.91542172 1473680.6037392   544320.68814666
 1325354.50823022  555811.40674295 1557276.06443164  605073.49080291
 1191564.19993432   31140.51762019 1179987.3238175  1578766.04995913
 1296146.93885966 1224454.54742604  953840.69760203  470008.13822756
 1067000.34947734 1377430.07217033  987004.08367438 1172730.15576932
  799191.03813568 1167421.73902776 1779858.27425291 1649947.15975202
 1506798.75490831 1258563.85864583  575694.17321584 1457755.97931771
  861138.18364013  900973.37639555 1619829.09572018  958909.19346485
 1677612.4421426  1390620.16815428 1535781.95982919 1218635.85140652
 1364832.00341912 1222412.01985409 1961846.90521895 1562842.63809466
 1259190.70620307 1442128.73191477  953840.69760203 1323300.71990284
 1232872.35617142 1336356.23256398 1098518.13368549 1246270.00968581
  569876.77488063 1364029.16836528 1076438.97514349  924346.16480242
  810537.14839216  938171.35555365  876348.81762484 1246830.18842863
 1584317.75269273 1312063.75611738 1114901.97262301  799191.03813568
 1641055.93904464 1570583.34033981 1921028.56988553 1750908.2242374
 1099959.63901248 2198564.57267471  975913.10514971  518831.47063278
  483458.54825829 1681340.63502116  671661.71344096 1609092.31792341
  568842.53557536  736897.40953719 1222041.01583291 1371311.61628979
  937628.34669366 1688642.67854484 1065679.12080299 1628490.7929731
  987355.96092124 1670950.31275687 1578493.70778387 1563193.09711859
  840124.84234532 1135676.18310429 1356062.10449866  939490.91384892
 1447920.68035935 1295728.08829687 1630438.85423015  885920.55324936
 1072914.9964424  1836419.64066846 1384140.22706635 1474546.76214611
 1389223.60712147 1335883.83118445 1154883.28760267 1432756.51709421
 1305101.77434224 1286400.91500907  565680.55280715  890887.68073159
  959416.43666204 1030866.951711   1369016.7779002  1097918.41234679
 1204103.086599   1048350.69182001  915818.45312156 1361230.12123516
  803689.15193809 1373290.86077854 1420283.55883776  698457.67764997
 1347279.20721747 1432902.75287187  998240.85078561 1437983.82471793
 1131040.70232425 1005392.41858925 1943359.76754111 1016871.41491422
 1059113.72127547 1360910.72833927 1474296.41581626 1570583.34033981
 1524845.42190295 1099959.63901248  143027.36445248  631656.47458267
 1077754.22596212 1126042.40497141 1274983.64807314  845553.3695012
 1286974.69672285 1129975.81711789 2105205.85586391 1924561.80717987
 1043628.37035454 1524115.89091551 1547888.6330482  1500481.75952471
 1420070.02039984 1213530.84986587 1587406.30285697 1412144.50844424
  832691.17813085 1214262.69927372 1131532.91943716 1827476.19606152
 1301486.6855461   891200.86227602 1218011.06078783  904789.61224402
 1624137.59543209 1523915.14468417 1257376.17368852 1432902.75287187
 1594415.22629122  565937.20055318 1630438.85423015 2146925.33988866
  552279.21404665 1392685.28507808 1198678.98429899 1514555.08213084
  885920.55324936  880084.70044787  787039.64467942  239319.93417545
  820250.38946581 1109665.5634039  1409439.06376517 1252733.09655161
 1324470.441475   1159207.08461659 1795630.91271501 1472337.69921632
 1340769.76782914  565680.55280715 1351007.0408581  1638577.41662703
 1129582.83842209 1275143.16840797 1347202.57758216 1126137.68140858
 1748474.69409409 1236044.31555322 1380602.55558134 1437458.36420179
  407718.93821549 1696086.16810427 1308017.31423918 1166925.14614882
 1473680.6037392  1348873.4268638   821598.98519505 1178553.61617926
 2082236.24379718  313651.50323329  942838.16472181 1273120.25882706
 1641055.93904464  585608.63262223  751952.57085914  615055.67579218
  790802.80103481 1228879.86701325 1419345.60730258 1479758.31752676
 1399909.04869688  742858.63563392 1887529.37663517 1765988.26353721
 1838984.43978839 1032180.37825914 1408427.75841093 1128895.12495077
 1914072.94778814  815190.65258117 1413579.81675087 1385776.50721725
 1659805.18404135 1369006.11488144 1388218.52944994 1190213.51290501
 1155752.74474026 1754969.16194479  736897.40953719 1360910.72833927
 1793398.71837966 1450996.03817929  890559.86102646 1248845.20903197
  954154.20689942 1009606.28363319 1372969.31074943 1114901.97262301
 1439506.10155701 1097918.41234679 1459525.37584855 1185743.82417968
 1438290.85142595 1371640.93171142  980983.21095236 1676770.33057392
 1275318.56220623 1078779.49709872 1211110.08408249  861321.58069247
 1531447.28528137 1043628.37035454 1741052.95962204 1012269.82010469
 1339303.6569164  1643086.27789701 2275455.30553244 1390620.16815428
  985283.88155783 1528987.32488161 1642011.34461186  450307.01738073
 1850513.52744405 1107159.78060591 1491838.49444347  849656.92319251
 1564125.23794177  986113.23949731 1434015.03263035 1200888.77269115
 1349818.25016203 1128720.4195686  1181630.62516964  404643.60224269
 1544379.74773568 1541746.29055905 1372549.78249221 1308017.31423918
 1047452.50808135 1573347.78844378  647982.6536393  1378269.57282251
 1356146.26084262  603714.7885822  1415073.61418119  852703.26367575
 1405399.85509825 1021122.05234751  839194.0689419   702321.75232142
 1615346.75000537 1532845.72311946 1150093.88886615  933306.28772076
 1309922.85417634 1222344.20849926  831762.7909034  1090888.96302923
 1125880.48737074 1125696.86236782 1167421.73902776 1454834.98247726
 1419345.60730258  759799.87583897 1039332.66738688  801348.58951135
 1184614.08702401 1153470.43974786 1004041.43483931 1379169.44873068
 1388782.88740135 1102943.35144492 1325819.91310847  779207.55461309
 1419345.60730258 1291331.51848582 1712282.25936342 1730103.13313233
 1256086.50705911  828497.06709607 1232974.142083    870252.41096443
 1064371.76412005 1036338.23901353  991892.31748425 1009142.33797403
 1286980.80741779 1708631.36537014  684049.91931112 1978629.87523252
 1598736.40016478  679228.99274684 1108022.2823717  1113647.87037207
  969678.5672888   866666.05537388 1686562.16857339 1437983.82471793
 1689512.17958956 1439506.10155701 1129388.12297668 1025417.88751949
 1205377.91104842 1891949.34783336 1798521.60452218 1059113.72127547]

In [9]:
from sklearn.metrics import mean_squared_error,mean_absolute_error

In [10]:
print(mean_squared_error(y_test,pre))

32946846689.81207

In [11]:
print(mean_absolute_error(y_test,pre))

143152.1220997813

# **data.csv**

In [12]:
df=pd.read_csv('data.csv')

In [13]:
df.head()

   R&D Spend  Administration  Marketing Spend       State    Profit
0   165349.2       136897.80         471784.1    New York  192261.8
1   162597.7       151377.60         443898.5  California  191792.1
2   153441.5       101145.60         407934.5     Florida  191050.4
3   144372.4       118671.90         383199.6    New York  182902.0
4   142107.3        91391.77         366168.4     Florida  166187.9

In [14]:
x=df[['R&D Spend','Administration','Marketing Spend']]
y=df[['Profit']]

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [16]:
from sklearn.tree import DecisionTreeRegressor
dtr=DecisionTreeRegressor()
dtr.fit(x_train,y_train)

DecisionTreeRegressor()

In [19]:
pre = dtr.predict(x_test)
print(pre)

[141585.5   78239.91  97483.56  49490.75 124266.9   14681.4  108552.
 101004.6  101004.6  141585.5 ]

In [20]:
from sklearn.metrics import mean_squared_error,mean_absolute_error

In [21]:
print(mean_squared_error(y_test,pre))

116223128.57700005

In [22]:
print(mean_absolute_error(y_test,pre))

8163.238