In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv(r"D:\AIML-internship\AllData\titanic.csv")

In [3]:
dataset

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [4]:
dataset.isnull()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
887,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False
889,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False

In [5]:
dataset.notnull()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True
887,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
888,True,True,True,False,True,True,True,True,True,True,True,False,True,True,True
889,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
890,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True

In [6]:
dataset.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [7]:
dataset.notnull().sum()

survived       891
pclass         891
sex            891
age            714
sibsp          891
parch          891
fare           891
embarked       889
class          891
who            891
adult_male     891
deck           203
embark_town    889
alive          891
alone          891
dtype: int64

In [8]:
mean_age=dataset["age"].mean()
m = np.round(mean_age,2)

In [9]:
dataset["age"] = dataset["age"].fillna(m)

In [10]:
dataset["age"].isnull().sum()

0

In [11]:
dataset["sex"] = dataset["sex"].replace('male','m')

In [12]:
dataset["sex"].unique()

array(['m', 'female'], dtype=object)

In [13]:
dataset["sex"] = dataset["sex"].replace('female','f')

In [23]:
dataset = pd.read_csv(r"D:\AIML-internship\AllData\weatherHistory.csv")

In [24]:
dataset

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
96448,2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31.0,16.1000,0.0,1014.36,Partly cloudy starting in the morning.
96449,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20.0,15.5526,0.0,1015.16,Partly cloudy starting in the morning.
96450,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30.0,16.1000,0.0,1015.66,Partly cloudy starting in the morning.
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20.0,16.1000,0.0,1015.95,Partly cloudy starting in the morning.
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39.0,15.5204,0.0,1016.16,Partly cloudy starting in the morning.

In [25]:
dataset.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.

In [26]:
dataset.isnull().sum()

Formatted Date                0
Summary                       0
Precip Type                 517
Temperature (C)               0
Apparent Temperature (C)      0
Humidity                      0
Wind Speed (km/h)             0
Wind Bearing (degrees)        0
Visibility (km)               0
Loud Cover                    0
Pressure (millibars)          0
Daily Summary                 0
dtype: int64

In [27]:
dataset = dataset.dropna()
dataset

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
96448,2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31.0,16.1000,0.0,1014.36,Partly cloudy starting in the morning.
96449,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20.0,15.5526,0.0,1015.16,Partly cloudy starting in the morning.
96450,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30.0,16.1000,0.0,1015.66,Partly cloudy starting in the morning.
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20.0,16.1000,0.0,1015.95,Partly cloudy starting in the morning.
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39.0,15.5204,0.0,1016.16,Partly cloudy starting in the morning.

In [28]:
dataset.isnull().sum()

Formatted Date              0
Summary                     0
Precip Type                 0
Temperature (C)             0
Apparent Temperature (C)    0
Humidity                    0
Wind Speed (km/h)           0
Wind Bearing (degrees)      0
Visibility (km)             0
Loud Cover                  0
Pressure (millibars)        0
Daily Summary               0
dtype: int64

In [29]:
data = []
for x in dataset['Temperature (C)']:
    ab = x+2
    ab1 = round(ab,2)
    data.append(ab1)

In [30]:
data

[11.47,
 11.36,
 11.38,
 10.29,
 10.76,
 11.22,
 9.73,
 10.77,
 12.82,
 15.77,
 18.02,
 19.14,
 19.8,
 19.33,
 20.88,
 20.91,
 17.39,
 17.55,
 16.26,
 15.14,
 13.55,
 13.18,
 12.12,
 12.2,
 12.42,
 11.91,
 13.18,
 9.16,
 8.11,
 8.79,
 9.26,
 9.8,
 11.87,
 14.22,
 17.09,
 19.36,
 21.01,
 22.04,
 23.05,
 23.18,
 22.12,
 22.22,
 22.0,
 19.8,
 18.06,
 17.02,
 16.42,
 16.26,
 15.77,
 15.28,
 10.63,
 13.25,
 13.18,
 12.69,
 13.11,
 13.11,
 14.17,
 14.76,
 15.84,
 18.18,
 19.52,
 19.38,
 19.36,
 19.21,
 17.63,
 15.58,
 12.91,
 10.8,
 10.96,
 10.2,
 9.69,
 9.77,
 10.2,
 10.18,
 9.31,
 9.64,
 8.62,
 8.68,
 8.09,
 8.07,
 8.14,
 9.13,
 9.21,
 9.57,
 10.9,
 11.96,
 11.89,
 13.07,
 12.12,
 13.04,
 12.65,
 12.05,
 11.9,
 10.79,
 9.83,
 9.86,
 9.32,
 9.24,
 7.44,
 9.2,
 8.69,
 8.21,
 8.11,
 8.11,
 8.17,
 9.22,
 9.29,
 9.41,
 9.96,
 10.03,
 11.08,
 11.05,
 11.05,
 11.18,
 11.07,
 9.98,
 10.07,
 9.89,
 9.31,
 9.34,
 8.62,
 8.07,
 10.34,
 7.18,
 5.72,
 6.86,
 7.21,
 8.26,
 9.79,
 12.05,
 14.2,
 14.7,
 15.93,
 17.09,
 17.15,
 18.18,
 18.25,
 18.29,
 18.1,
 14.96,
 15.85,
 14.78,
 14.15,
 12.68,
 12.44,
 11.82,
 13.03,
 9.14,
 9.62,
 9.63,
 9.04,
 10.6,
 11.65,
 14.11,
 14.78,
 15.81,
 18.02,
 19.13,
 19.14,
 19.78,
 19.78,
 19.81,
 18.16,
 16.05,
 15.09,
 14.29,
 14.78,
 14.73,
 14.27,
 13.71,
 12.83,
 14.2,
 14.2,
 13.69,
 13.21,
 13.13,
 13.44,
 15.03,
 19.24,
 19.74,
 19.84,
 20.86,
 20.67,
 19.82,
 19.8,
 19.35,
 18.07,
 16.93,
 15.92,
 14.76,
 14.76,
 14.37,
 13.18,
 13.67,
 10.98,
 12.58,
 12.53,
 12.59,
 11.98,
 13.02,
 15.54,
 15.89,
 17.0,
 19.18,
 18.2,
 19.75,
 20.41,
 19.82,
 19.31,
 19.51,
 19.27,
 17.14,
 15.25,
 14.29,
 12.7,
 11.86,
 11.52,
 10.41,
 15.01,
 9.73,
 8.14,
 8.47,
 8.63,
 10.69,
 13.99,
 15.77,
 17.09,
 18.46,
 19.31,
 19.87,
 21.04,
 20.98,
 21.01,
 21.01,
 19.87,
 19.27,
 18.19,
 16.88,
 16.33,
 16.51,
 16.37,
 16.88,
 12.41,
 14.82,
 14.8,
 14.83,
 14.27,
 14.27,
 14.18,
 14.17,
 14.71,
 17.61,
 18.02,
 19.2,
 19.22,
 19.83,
 19.83,
 19.73,
 18.27,
 15.17,
 15.26,
 15.01,
 14.46,
 14.49,
 11.56,
 12.62,
 10.72,
 12.53,
 11.44,
 11.89,
 12.37,
 10.89,
 11.98,
 14.2,
 15.96,
 16.94,
 18.18,
 18.37,
 19.37,
 19.67,
 19.72,
 18.24,
 16.07,
 15.96,
 14.29,
 12.02,
 11.38,
 11.42,
 13.83,
 12.76,
 14.16,
 11.67,
 10.15,
 12.2,
 12.12,
 12.16,
 13.24,
 14.24,
 15.91,
 17.62,
 17.07,
 17.07,
 16.27,
 18.02,
 17.03,
 15.94,
 14.92,
 14.89,
 14.4,
 14.27,
 14.22,
 13.25,
 13.53,
 13.54,
 11.44,
 13.44,
 13.39,
 13.53,
 13.95,
 13.97,
 14.63,
 14.76,
 15.84,
 15.17,
 17.07,
 19.24,
 18.32,
 19.38,
 17.27,
 19.46,
 18.22,
 17.08,
 15.99,
 14.17,
 13.09,
 13.09,
 11.88,
 11.36,
 11.86,
 10.27,
 10.87,
 10.82,
 9.16,
 10.85,
 13.18,
 14.39,
 16.14,
 19.1,
 20.94,
 19.92,
 21.98,
 22.07,
 22.07,
 22.08,
 21.09,
 19.45,
 17.57,
 14.49,
 14.24,
 13.42,
 12.56,
 12.47,
 12.25,
 11.36,
 10.31,
 10.81,
 10.73,
 13.93,
 16.52,
 20.73,
 22.03,
 23.04,
 22.74,
 24.32,
 24.11,
 24.73,
 24.78,
 23.22,
 22.18,
 20.01,
 19.42,
 15.96,
 15.29,
 14.32,
 13.12,
 12.53,
 14.38,
 11.86,
 10.87,
 10.67,
 9.69,
 12.91,
 16.84,
 20.8,
 23.09,
 24.03,
 24.83,
 24.92,
 25.92,
 25.91,
 25.93,
 25.92,
 24.82,
 23.23,
 21.08,
 19.06,
 16.91,
 15.08,
 14.71,
 14.13,
 13.81,
 14.02,
 14.04,
 12.63,
 11.91,
 14.56,
 17.01,
 19.34,
 21.1,
 23.26,
 24.41,
 24.94,
 25.93,
 25.96,
 25.96,
 25.11,
 24.82,
 23.11,
 20.19,
 18.02,
 17.47,
 16.61,
 15.31,
 14.73,
 15.79,
 12.58,
 12.48,
 12.29,
 11.97,
 15.64,
 18.74,
 20.84,
 23.16,
 24.59,
 24.89,
 26.01,
 26.01,
 25.98,
 27.04,
 26.08,
 24.38,
 23.21,
 20.26,
 19.2,
 17.99,
 17.96,
 17.44,
 16.37,
 15.61,
 14.82,
 14.75,
 13.42,
 14.33,
 16.91,
 17.89,
 19.23,
 19.83,
 19.92,
 21.06,
 22.14,
 22.26,
 23.21,
 23.26,
 22.23,
 21.08,
 19.94,
 17.49,
 16.14,
 16.54,
 16.14,
 15.4,
 15.43,
 13.59,
 16.42,
 15.92,
 15.4,
 15.87,
 16.91,
 17.93,
 19.13,
 20.75,
 20.96,
 21.99,
 23.11,
 23.09,
 23.18,
 23.23,
 22.1,
 21.03,
 19.85,
 18.26,
 16.98,
 16.47,
 15.94,
 14.32,
 13.76,
 12.83,
 12.14,
 12.63,
 12.61,
 12.07,
 13.16,
 14.89,
 17.05,
 17.16,
 18.27,
 19.8,
 19.94,
 20.86,
 19.99,
 19.96,
 19.36,
 18.25,
 16.12,
 14.95,
 14.24,
 13.69,
 13.16,
 11.22,
 10.68,
 11.19,
 10.59,
 9.51,
 8.22,
 7.86,
 7.93,
 12.41,
 14.54,
 15.86,
 17.98,
 19.27,
 19.84,
 18.43,
 19.78,
 19.84,
 19.3,
 17.18,
 15.01,
 14.69,
 14.19,
 14.08,
 12.62,
 13.6,
 13.02,
 13.89,
 12.42,
 12.3,
 11.48,
 11.77,
 12.93,
 13.66,
 15.94,
 17.03,
 18.04,
 17.23,
 18.21,
 19.3,
 19.78,
 19.8,
 19.26,
 19.2,
 17.02,
 15.93,
 14.37,
 14.29,
 14.79,
 11.53,
 11.97,
 6.91,
 9.92,
 9.38,
 9.97,
 10.82,
 10.79,
 9.89,
 9.8,
 9.82,
 9.94,
 10.08,
 12.23,
 13.36,
 14.45,
 14.92,
 14.55,
 14.38,
 12.23,
 11.23,
 9.83,
 8.68,
 8.12,
 7.33,
 6.36,
 11.27,
 6.26,
 5.22,
 5.91,
 4.71,
 5.82,
 8.88,
 10.94,
 13.21,
 14.85,
 15.96,
 16.98,
 16.03,
 17.02,
 17.04,
 17.09,
 16.95,
 15.82,
 14.92,
 15.84,
 14.76,
 14.65,
 13.69,
 12.63,
 7.67,
 12.05,
 11.98,
 11.78,
 10.66,
 9.55,
 9.23,
 8.04,
 8.09,
 8.12,
 8.07,
 8.04,
 8.89,
 9.06,
 8.04,
 8.07,
 7.04,
 7.02,
 7.03,
 7.0,
 6.98,
 6.93,
 6.47,
 6.44,
 6.01,
 6.91,
 6.88,
 6.39,
 6.84,
 6.81,
 6.94,
 9.2,
 9.78,
 10.73,
 10.98,
 12.0,
 12.09,
 13.06,
 12.14,
 13.01,
 12.12,
 9.92,
 9.33,
 7.05,
 5.93,
 6.09,
 5.8,
 4.69,
 7.07,
 4.6,
 3.58,
 4.16,
 2.96,
 2.96,
 7.59,
 11.82,
 13.07,
 13.06,
 14.24,
 14.85,
 14.89,
 14.92,
 15.89,
 15.02,
 14.38,
 12.21,
 11.14,
 9.83,
 9.73,
 9.14,
 8.02,
 7.46,
 10.24,
 5.84,
 4.24,
 4.02,
 4.17,
 5.66,
 8.11,
 12.01,
 14.24,
 14.94,
 15.98,
 17.09,
 18.25,
 19.27,
 19.29,
 19.39,
 19.29,
 17.09,
 13.71,
 13.16,
 12.03,
 12.14,
 23.02,
 21.44,
 22.72,
 20.79,
 19.73,
 19.61,
 20.73,
 24.56,
 26.76,
 29.17,
 30.91,
 32.96,
 34.17,
 34.13,
 33.98,
 34.54,
 33.98,
 34.01,
 32.94,
 30.57,
 29.09,
 26.69,
 26.14,
 25.12,
 17.56,
 17.49,
 18.54,
 15.8,
 15.32,
 14.61,
 14.33,
 16.97,
 18.26,
 18.25,
 20.89,
 23.35,
 23.21,
 24.34,
 25.03,
 25.91,
 26.98,
 25.8,
 25.59,
 24.51,
 22.02,
 21.91,
 21.36,
 19.88,
 19.25,
 18.63,
 17.84,
 19.0,
 19.07,
 18.51,
 16.98,
 18.02,
 18.16,
 20.84,
 23.12,
 24.51,
 25.79,
 25.89,
 27.83,
 27.93,
 27.0,
 26.94,
 26.93,
 24.8,
 21.34,
 19.81,
 19.78,
 18.49,
 17.69,
 17.63,
 18.21,
 17.58,
 17.58,
 17.61,
 17.05,
 19.07,
 19.48,
 19.67,
 20.8,
 21.68,
 20.82,
 22.0,
 23.15,
 25.66,
 25.62,
 25.82,
 24.04,
 21.95,
 20.92,
 19.27,
 18.18,
 17.83,
 18.73,
 18.71,
 18.27,
 18.14,
 18.09,
 17.56,
 16.52,
 19.09,
 19.67,
 21.79,
 24.02,
 23.14,
 23.04,
 20.94,
 20.92,
 22.05,
 23.07,
 22.05,
 22.0,
 20.87,
 19.96,
 19.71,
 19.73,
 18.79,
 18.67,
 18.16,
 19.01,
 18.12,
 18.12,
 17.56,
 16.01,
 18.12,
 18.05,
 18.21,
 19.81,
 20.88,
 22.19,
 24.27,
 24.36,
 25.87,
 25.89,
 24.96,
 24.48,
 22.86,
 21.16,
 19.73,
 20.24,
 19.82,
 19.71,
 19.2,
 17.31,
 18.55,
 18.09,
 17.55,
 16.93,
 19.09,
 20.66,
 21.81,
 23.06,
 24.21,
 24.75,
 25.79,
 25.48,
 25.96,
 26.95,
 25.96,
 25.96,
 25.86,
 21.27,
 19.29,
 18.62,
 18.67,
 17.07,
 16.52,
 19.84,
 16.44,
 15.89,
 16.43,
 16.93,
 19.04,
 20.79,
 23.16,
 25.87,
 26.97,
 28.13,
 29.22,
 29.74,
 29.78,
 29.8,
 29.87,
 28.16,
 25.98,
 24.57,
 23.14,
 22.44,
 22.43,
 21.36,
 20.75,
 21.88,
 19.22,
 18.64,
 18.55,
 18.09,
 19.67,
 22.78,
 24.73,
 28.02,
 28.13,
 30.84,
 31.01,
 33.03,
 33.13,
 33.13,
 33.21,
 32.02,
 29.87,
 27.41,
 24.76,
 24.69,
 23.2,
 23.55,
 23.44,
 21.51,
 21.86,
 21.33,
 20.75,
 20.84,
 21.91,
 24.11,
 26.95,
 27.0,
 29.3,
 29.97,
 32.12,
 33.04,
 33.21,
 34.17,
 34.54,
 33.04,
 30.96,
 28.48,
 24.92,
 25.38,
 24.45,
 24.6,
 21.98,
 22.96,
 20.87,
 20.34,
 20.85,
 19.28,
 21.92,
 25.6,
 27.99,
 29.73,
 30.79,
 31.88,
 32.97,
 33.92,
 34.13,
 34.13,
 33.08,
 33.02,
 29.27,
 27.46,
 24.8,
 25.22,
 24.24,
 22.42,
 21.88,
 18.81,
 21.38,
 20.87,
 20.88,
 19.87,
 20.94,
 22.09,
 23.09,
 24.18,
 25.53,
 25.84,
 26.96,
 27.92,
 26.96,
 ...]

In [31]:
dataset['New_temp'] = data
dataset

C:\Users\Admin\AppData\Local\Temp\ipykernel_13528\1808263490.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset['New_temp'] = data

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary,New_temp
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.,11.47
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.,11.36
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.,11.38
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.,10.29
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.,10.76
...,...,...,...,...,...,...,...,...,...,...,...,...,...
96448,2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31.0,16.1000,0.0,1014.36,Partly cloudy starting in the morning.,28.02
96449,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20.0,15.5526,0.0,1015.16,Partly cloudy starting in the morning.,26.58
96450,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30.0,16.1000,0.0,1015.66,Partly cloudy starting in the morning.,24.04
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20.0,16.1000,0.0,1015.95,Partly cloudy starting in the morning.,23.52
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39.0,15.5204,0.0,1016.16,Partly cloudy starting in the morning.,22.44

In [32]:
dataset.insert(2,"Temp_update",data)
dataset

,Formatted Date,Summary,Temp_update,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary,New_temp
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,11.47,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.,11.47
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,11.36,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.,11.36
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,11.38,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.,11.38
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,10.29,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.,10.29
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,10.76,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.,10.76
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96448,2016-09-09 19:00:00.000 +0200,Partly Cloudy,28.02,rain,26.016667,26.016667,0.43,10.9963,31.0,16.1000,0.0,1014.36,Partly cloudy starting in the morning.,28.02
96449,2016-09-09 20:00:00.000 +0200,Partly Cloudy,26.58,rain,24.583333,24.583333,0.48,10.0947,20.0,15.5526,0.0,1015.16,Partly cloudy starting in the morning.,26.58
96450,2016-09-09 21:00:00.000 +0200,Partly Cloudy,24.04,rain,22.038889,22.038889,0.56,8.9838,30.0,16.1000,0.0,1015.66,Partly cloudy starting in the morning.,24.04
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,23.52,rain,21.522222,21.522222,0.60,10.5294,20.0,16.1000,0.0,1015.95,Partly cloudy starting in the morning.,23.52
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,22.44,rain,20.438889,20.438889,0.61,5.8765,39.0,15.5204,0.0,1016.16,Partly cloudy starting in the morning.,22.44

In [33]:
del dataset['Temperature (C)']
dataset

,Formatted Date,Summary,Temp_update,Precip Type,Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary,New_temp
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,11.47,rain,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.,11.47
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,11.36,rain,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.,11.36
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,11.38,rain,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.,11.38
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,10.29,rain,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.,10.29
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,10.76,rain,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.,10.76
...,...,...,...,...,...,...,...,...,...,...,...,...,...
96448,2016-09-09 19:00:00.000 +0200,Partly Cloudy,28.02,rain,26.016667,0.43,10.9963,31.0,16.1000,0.0,1014.36,Partly cloudy starting in the morning.,28.02
96449,2016-09-09 20:00:00.000 +0200,Partly Cloudy,26.58,rain,24.583333,0.48,10.0947,20.0,15.5526,0.0,1015.16,Partly cloudy starting in the morning.,26.58
96450,2016-09-09 21:00:00.000 +0200,Partly Cloudy,24.04,rain,22.038889,0.56,8.9838,30.0,16.1000,0.0,1015.66,Partly cloudy starting in the morning.,24.04
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,23.52,rain,21.522222,0.60,10.5294,20.0,16.1000,0.0,1015.95,Partly cloudy starting in the morning.,23.52
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,22.44,rain,20.438889,0.61,5.8765,39.0,15.5204,0.0,1016.16,Partly cloudy starting in the morning.,22.44